version: "3.8"
services:
    # Mysql database container
    db:
        image: mysql
        container_name: fit-tracker-db
        restart: always
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        networks:
            - fit-tracker

    # phpmyadmin container
    phpmyadmin:
        image: phpmyadmin
        container_name: fit-tracker-phpmyadmin
        restart: always
        depends_on:
            - db
        ports:
            - 8080:80
        environment:
            PMA_HOST: db
        networks:
            - fit-tracker

    # Symfony apache project container
    www:
        build: docker/php
        container_name: fit-tracker-php
        ports:
          - "8000:80"
        volumes:
            - ./docker/php/vhosts:/etc/apache2/sites-enabled
            - ./:/var/www
        restart: always
        networks:
            - fit-tracker

networks:
    fit-tracker:

volumes:
    db-data: