auth:
    path: /api/auth
    methods: ['POST']

get_chart:
    path: '/api/charts/{exerciseId}'
    controller: 'FitTrackerApi\Controller\ChartController::getChart'
    methods: ['GET']

privacy:
    path: '/privacy'
    controller: 'FitTrackerApi\Controller\PrivacyController::index'
    methods: ['GET']
  
delete_my_account:
    path: '/delete-my-account'
    controller: 'FitTrackerApi\Controller\DeleteInstructionsController::index'
    methods: ['GET']