name: Close Issue on accepted pull request

run-name: ${{ github.actor }} has accepted a PR, the related issue will be closed! 🚀

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  close-issue:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Close Issue
        run: |
          ISSUE_NUMBER=$(jq -r ".pull_request.head.ref" $GITHUB_EVENT_PATH | cut -d'-' -f1)
          echo "https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/${ISSUE_NUMBER}"
          echo "token : ${GITHUB_TOKEN}"
          echo "other : ${{ secrets.GITHUB_TOKEN }}"
          curl -L \
            -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/${ISSUE_NUMBER}" \
            -d '{"state":"closed"}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


