name: Close Issue on accepted pull request

run-name: ${{ github.actor }} has accepted a PR, the related issue will be closed 🚀

on:
  pull_request:
    types:
      - closed

jobs:
  close-issue:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Close Issue
        run: |
          ISSUE_NUMBER=$(jq -r ".pull_request.head.ref" $GITHUB_EVENT_PATH | cut -d'-' -f1)
          echo "https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/${ISSUE_NUMBER}"
          curl -L \
            -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/${ISSUE_NUMBER} \
            -d '{"state":"closed"}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


