name: Close Issue on accepted pull request

run-name: ${{ github.actor }} has accepted a PR, the related issue will be closed! 🚀

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  close-issue:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Close Issue
        run: |
          ISSUE_NUMBER=$(jq -r ".pull_request.head.ref" $GITHUB_EVENT_PATH | cut -d'-' -f1)
          curl -L \
            -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/${ISSUE_NUMBER}" \
            -d '{"state":"closed"}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  delete-branch:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Delete Branch
        run: |
          BRANCH_NAME=$(echo ${{ github.event.pull_request.head.ref }})
          echo $BRANCH_NAME
          curl -X DELETE \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${GITHUB_REPOSITORY}/git/refs/heads/${BRANCH_NAME}"

