name: Create branch on new issue

run-name: ${{ github.actor }} has created a new issue, a branch is being created 🚀

on: 
  issues:
    types: 
      - opened
    
jobs:
  create-branch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Debug Information
        run: |
          git status
          git branch
          git remote -v
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Branch
        run: |
          ISSUE_NUMBER=$(jq -r ".issue.number" $GITHUB_EVENT_PATH)
          ISSUE_TITLE=$(jq -r ".issue.title" $GITHUB_EVENT_PATH)
          BRANCH_NAME="$ISSUE_NUMBER-$ISSUE_TITLE"
          echo "Branch $BRANCH_NAME will be automatically created"
          git checkout -b "$BRANCH_NAME"
          git push origin "$BRANCH_NAME"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}