name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing action on create issue 🚀
on: 
  issues:
    types: [opened]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Create Branch
        run: |
          ISSUE_NUMBER=$(jq -r ".issue.number" $GITHUB_EVENT_PATH)
          ISSUE_TITLE=$(jq -r ".issue.title" $GITHUB_EVENT_PATH)
          BRANCH_NAME="$ISSUE_NUMBER-$ISSUE_TITLE"
          echo "Branch $BRANCH_NAME will be automatically created"
          git checkout -b "$BRANCH_NAME"
          git push origin "$BRANCH_NAME"